name: flutter_fitness_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.9.0
  step_progress_indicator: ^0.2.0+3
  font_awesome_flutter: ^8.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: QuickSandBold
      fonts:
        - asset: assets/fonts/quicksand_bold.ttf

    - family: QuickSandMed
      fonts:
        - asset: assets/fonts/quicksand_med.ttf
    - family: QuickSandSemiBold
      fonts:
          - asset: assets/fonts/quicksand_semibold.ttf
    - family: QuickSand
      fonts:
          - asset: assets/fonts/quicksand_reg.ttf
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  uses-material-design: true
